### ISSUE TITLE
rust and cargo stages can't be fetched via https 

### ISSUE THREAD

**Issue by stefson** [smaeul/portage-overlay#13]
hey there, I just noticed that the ssl encryption of portage.smaeul.xyz doesn't work anymore. The certificate is invalid since a few days - using wget --no-check-certificate still works, but propably not the best idea.

**Comment by smaeul** [comment]
Thanks for the report. My acme client got removed when I switched from libressl to openssl, so the program responsible for renewing the certificates was missing. I've switched to a more reliable solution, so it shouldn't happen again.
