### ISSUE TITLE
rust pr64823 

### ISSUE THREAD

**Issue by stefson** [smaeul/portage-overlay#21]
hey there, I just noticed the increase of size in your new rust-1.38 stages, and wanted to notify you of an still ongoing pullrequest that should fix that: https://github.com/rust-lang/rust/pull/64823

This was later reverted, it might be that https://github.com/rust-lang/rust/pull/65474 is the one that is actually going to fix this.

**Comment by smaeul** [comment]
Thanks for letting me know! I don't mind the space usage for now, since it looks like it'll be taken care of upstream. I'll get the fix when it goes stable.
