### ISSUE TITLE
=dev-lang/rust-1.38.0 fails to execute cargo build on git checkout with: invalid version 0 on git_proxy_options; class=Invalid

### ISSUE THREAD

**Issue by stefson** [smaeul/portage-overlay#22]
```user@tuxbox ~/cranelift $ cargo build
    Updating crates.io index
error: failed to load source for a dependency on `capstone`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  invalid version 0 on git_proxy_options; class=Invalid (3)
```

a quick google search shows hints of a possible issue with libgit2?

**Comment by smaeul** [comment]
The rust bindings are incompatible with the last released version of `libgit2` (https://github.com/rust-lang/git2-rs/issues/458). I actually have a patch for this issue. It looks, though, like the system `libgit2` isn't getting linked like it should be. So the patch ends up breaking the bundled `libgit2`. I'm testing a fix for this; in the meantime, remove patch 0032.

**Comment by stefson** [comment]
you're right, it's patch 0032-* at fault here. 

I never have had a sort of system `dev-libs/libgit2` emerged, is it a dependency at runtime?

**Comment by stefson** [comment]
I can confirm, it's working now :)
