### ISSUE TITLE
Rust fails to build using the armv7a-unknown-linux-musleabihf target

### ISSUE THREAD

**Issue by imapotatoalso** [smaeul/portage-overlay#25]
[buildlog.txt](https://github.com/smaeul/portage-overlay/files/5189886/buildlog.txt)
[emergeinfo.txt](https://github.com/smaeul/portage-overlay/files/5189887/emergeinfo.txt)

**Comment by smaeul** [comment]
Upgrade your musl to at least 1.2.0, which enables time64 support -- see http://musl.libc.org/releases.html

**Comment by imapotatoalso** [comment]
Thank you it worked :)
