### ISSUE TITLE
dev-lang/rust-1.20.0 fails to build on musl-amd64 due to missing symbols in llvm 

### ISSUE THREAD

**Issue by stefson** [smaeul/portage-overlay#4]
The emerge fails right at the start of src_compile. However, the symbols which cannot be found are in fact present in the files mentionend. Executing readelf and greping for the symbol gives me

user lib # readelf -Ws librustc_llvm-39a99d7b84a2fef8.so | grep _ZNSt6thread6_StateD2Ev
    74: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZNSt6thread6_StateD2Ev@GLIBCXX_3.4.22 (10)
 28341: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZNSt6thread6_StateD2Ev@@GLIBCXX_3.4.22

and for the second symbol

user lib # readelf -Ws librustc_llvm-39a99d7b84a2fef8.so | grep _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE
   150: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE@GLIBCXX_3.4.22 (10)
 32799: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE@@GLIBCXX_3.4.22

full build log

[rust-build-log.gz](https://github.com/smaeul/portage-overlay/files/1293115/rust-build-log.gz)

**Comment by stefson** [comment]
snippet from emerge --info 
```
Timestamp of repository gentoo: Mon, 11 Sep 2017 12:45:01 +0000
sh bash 4.3_p48-r1
ld GNU ld (Gentoo 2.28.1 p1.0) 2.28.1
app-shells/bash:          4.3_p48-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.24.1-r2::gentoo
dev-lang/python:          2.7.12::gentoo, 3.4.5::gentoo
dev-util/cmake:           3.7.2::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.3::gentoo
sys-apps/openrc:          0.28::gentoo
sys-apps/sandbox:         2.10-r3::musl
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.12.6::gentoo, 1.15-r2::gentoo
sys-devel/binutils:       2.28.1::gentoo
sys-devel/gcc:            5.4.0-r3::musl
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1::gentoo
sys-kernel/linux-headers: 4.4::musl (virtual/os-headers)
sys-libs/musl:            1.1.16::gentoo
```
full output of emerge --info
[emerge.info.gz](https://github.com/smaeul/portage-overlay/files/1293233/emerge.info.gz)

**Comment by smaeul** [comment]
Looks like it's because I have GCC 6 and you're still on GCC 5. I think I can rebuild everything with libstdc++ built in statically, so I'll do that.

**Comment by stefson** [comment]
If libstdc++ is linked statically by you, does that mean I'll be able to use GCC 4.9 as well to build rust? GCC 5.4 is not really stabilized on arm :/ 

(The cargo ebuild works on amd64)

**Comment by stefson** [comment]
The point about GCC 5 breakage on arm is true, but it has been fixed in the musl overlay so it should not be of a big concern to you. I use a mainly stable keywords system and occasionally test packages from unstable such as firefox. I wanted to wait for the new 17.0 profile to switch over to GCC 6, but I could use a chroot to test it with amd64 and tell you if your rust stages are working as intended. Honestly I can imagine it to get a bit hairy with a static libstdc++ 

Or I could try to build an own stage 0 from my glibc system with gcc 5, following your advice from the thread at the musl overlay? :)

**Comment by smaeul** [comment]
stage0s now have libstdc++ linked statically, so your GCC version should be irrelevant now.
