### ISSUE TITLE
flawed logic of detecting chost in dev-lang/rust and dev-util/cargo ebuild

### ISSUE THREAD

**Issue by stefson** [smaeul/portage-overlay#6]
Something is wrong here, most likely with the way your ebuild does construct the filename of the apropiate stage0 for the given toolchain 

`ebuild rust-1.20.0.ebuild fetch`
 * rustc-1.20.0-src.tar.gz SHA256 size ;-) ...                                                                                                                                   [ ok ]
!!! Fetched file: rust-1.19.0-armv7a-hardfloat-linux-musleabi.tar.xz VERIFY FAILED!
!!! Reason: Insufficient data for checksum verification
!!! Got:      
!!! Expected: MD5 RMD160 SHA1 SHA256 SHA512 WHIRLPOOL

this is what the ebuild expects to find at SRC_URI: rust-1.19.0-armv7a-hardfloat-linux-musleabi.tar.xz

while this is the name of the file which you host: rust-1.19.0-armv7-unknown-linux-musleabihf.tar.xz

The manifest only has the checksums of the amd stage0 I guess (rust-1.19.0-x86_64-unknown-linux-musl.tar.xz) and the src file from upstream, so I believe that a user with a x86 installation would run into this as well. 

The cargo ebuild suffers from the same error. 

It might be possible to work around this by adding customized CTARGET=$ values and activating those with use amd64 && in front of it, or use arm && ; but I don't feel very confident with editing these variables on my own :) 

There is also an issue with slots of dev-lang/rust - in the output of `eix dev-lang/rust` they show up as 

`(stable) ~*1.15.1(stable/1.15) ~*1.16.0(stable/1.16) ~*1.19.0(stable/1.19) ~*1.20.0(stable/(get_version_component_range 1-2))[1]` 

while it should be (stable/1.20) for your ebuild from the overlay. It might not be harmfull, but I could imagine it to become a problem when changing slots in the future, or when ebuilds check for a certain slot/subslot of rust.

**Comment by stefson** [comment]
These are the checksums for the Manifest for the stage0's linked statically against libstdc++ ; I bypassed the fancy CTARGET variables for now and replaced them localy with the value I need for armv7hf 

DIST cargo-0.20.0-armv7-unknown-linux-musleabihf.tar.xz 2723968 SHA256 b578e3d78c83547052b928423f729ecde81b1d092d9d9c4acaf9626ebd667fe2 SHA512 d03941f84d312be85b1ebb66d1fd1e8ac6fc62514ff618c8296c581b5704c3dcb39d495244a0aaa174839ef12f6c6c10d445071cdf38727e3af18b3b9af59e07 WHIRLPOOL a55b19022b9bb09001382f9428f3506b4d0c635c910cdf2583834a47c4619fabfbc58937a8fd0f3dee60254f0a0b8329bf6ac2ba8091461d40bc117d5c7edf60

DIST rust-1.19.0-armv7-unknown-linux-musleabihf.tar.xz 54016148 SHA256 f9dc04d3da90421ae6a76190435872574a3f3416a931ce476136276e994fa28a SHA512 c34e90029144874ff1bfb3d6cd8abee7a1cf240cabda144144586f67f328a9b74ae868d297366d4d6c6693d88c3193febb62822c919071aabb7983911d1b333b WHIRLPOOL 7690a3e45b85a35e5752a578c5524e08eed40c293d8343fa402f39bcd8744afc1ad3c3adade8883fb03f96ea03ab3cade9e963a87219664a0243a7b261b34429

**Comment by stefson** [comment]
To fix the CHOST variable for arm and x86 without breaking the existing is non trivial. Thought about something like this 

`use amd && CHOST="x86_64-unknown-linux-musl"`
`use arm && CHOST="armv7-unknown-linux-musleabihf"`
`use x86 && CHOST="i686-unknown-linux-musl"`

but this is not allowed to be set before either src_setup or src_prepare and therefore useless for solving the issue.

**Comment by smaeul** [comment]
The correct solution here is to just create an `arm-unknown-linux-musleabi` stage0, which is what I'm doing now

**Comment by smaeul** [comment]
The difference between the stage0's I generated and the stage2 rustc you have installed on your system is that the stage0's were compiled with static LLVM and `extended = true` in `config.toml`. This makes them include cargo as well, which has more dependencies:
* `libcurl`
* `libhttp_parser`
* `libssh2`
* `openssl`
Other than the stage0's being more batteries-included (and therefore more portable), there's no functional difference from the stage2 you have installed on your system.

**Comment by smaeul** [comment]
@stefson I got the fix for stage0's on different architectures committed with the update to 1.21.0 I just pushed. Please let me know if it works like you expect.

**Comment by stefson** [comment]
I tested with amd64 and dev-lang/rust fails very early in the bootstrap process with a linking error. 
logs are here: [build.log.zip](https://github.com/smaeul/portage-overlay/files/1390230/build.log.zip) [emerge-info.zip](https://github.com/smaeul/portage-overlay/files/1390238/emerge-info.zip)
 emerge -pv dev-lang/rust::smaeul --nodeps

These are the packages that would be merged, in order:

[ebuild     U ~] dev-lang/rust-1.21.0:stable/1.21::smaeul [1.20.0:stable/1.20::smaeul] USE="-debug -doc -jemalloc -system-llvm" 0 KiB

Total: 1 package (1 upgrade), Size of downloads: 0 KiB

**Comment by stefson** [comment]
armhf fails because it cannot find the file "work/rust-1.20.0-armv7a-hardfloat-linux-musleabi/install.sh" (maybe some variable typo/error in the ebuild?)

[armhf-logs.zip](https://github.com/smaeul/portage-overlay/files/1390460/armhf-logs.zip)

These are the packages that would be merged, in order:

[ebuild U ~] dev-lang/rust-1.21.0:stable/1.21::smaeul [1.20.0:stable/1.20::smaeul] USE="-debug -doc -jemalloc -system-llvm" 0 KiB

Total: 1 package (1 upgrade), Size of downloads: 0 KiB

**Comment by smaeul** [comment]
@stefson Thanks! I'm not sure how you got the linking error on amd64 while I have not... it should be failing for me as well (that was an actual bug in one of my patches). I've pushed updates for both issues, and I'm rebuilding stage0's to fix the linking error.

It's really annoying how Gentoo on arm does its build triples. I have to convert `armv7a-hardfloat-linux-musleabi` into `armv7-unknown-linux-musleabihf`, because that's what rust expects.

**Comment by stefson** [comment]
Okay, now on arm the ebuild wants to source for rust-1.20.0-arm**v7**-unknown-linux-musleabi**hf**.tar.xz but cannot find it, because there is only rust-1.20.0-arm-unknown-linux-musleabi.tar.xz in the manifest. 

I know this is really painfull to solve, and all I can say is that it is way above my head from the intellectuall point of view :-/

**Comment by smaeul** [comment]
It's in the manifest locally on my machine, but I haven't pushed because the checksums will all change when I finish rebuilding the stage0's.

**Comment by stefson** [comment]
Build passes on amd64 for both cargo and rust, but got busted for arm. I have not yet tried to compile rust, but for cargo the ebuild does download both archives, cargo-0.21.0-arm-unknown-linux-musleabi and cargo-0.21.0-armv7-unknown-linux-musleabihf; it extracts them and fails right at the start of src_compile because it cannot find the cargo binary: 

``>>> Compiling source in /var/tmp/portage/dev-util/cargo-0.22.0/work/cargo-0.22.0 ...
/var/tmp/portage/dev-util/cargo-0.22.0/temp/environment: line 2528: /var/tmp/portage/dev-util/cargo-0.22.0/work/cargo-0.21.0-armv7a-hardfloat-linux-musleabi/cargo/bin/cargo: No such file or directory``

please note the missing hf and 7a suffix in the environement.

**Comment by smaeul** [comment]
Try cargo on arm now? I forgot to copy the triple-mangling code from rust to cargo.

**Comment by stefson** [comment]
The compile passes now for musl on armhf! :) 

Do you want me to check if your ebuild works as well for glibc based arm? 
And do you happen to know a programm written in rust which I could use to see if there are any runtime issues? Firefox won't work because there is a segfault at startup (which is very likely related to spidermonkey and not rust)

Are you open to try to fix the honoring of MAKEOPTS in the ebuild? It is a problem for arm, or debug builds with a ratio of less then 3gb ram per core aifak. The compile of rust takes forever if it hits the swap and may never finish in some cases - for a quadcore with HT in debug mode it would be ~24gb :/  

x.py build -j $({MAKEOPTS}) does not work, right? 

Or maybe introduce a low-memory useflag and try to constuct some if ; then x.py build commands based upon this useflag, or its absence?

**Comment by smaeul** [comment]
> Do you want me to check if your ebuild works as well for glibc based arm?

That would be great!

> And do you happen to know a program written in rust which I could use to see if there are any runtime issues? Firefox won't work because there is a segfault at startup (which is very likely related to spidermonkey and not rust).

There's cargo, of course, which is compiled with the installed copy of Rust. Another good program to test would be `sys-apps/ripgrep`.

**Comment by stefson** [comment]
The ebuild works with glibc :) I used rust-1.21.0 and cargo 0.22.0 before you commited those three changes yesterday and testcompiled sys-apps/ripgrep, and tested with the firefox ebuild up to src_configure if I really have an armv7-hardfloat rustc, which is the case.

**Comment by smaeul** [comment]
Ok, I think this is resolved now.
